on:
  workflow_dispatch:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
  create:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'magisk-module-vili-jp-felica.zip'
        exclusions: '*.git*'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "magisk-module-vili-jp-felica.zip"
        token: ${{ secrets.GITHUB_TOKEN }}